package com.spring.hrms.core.mernis;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 8.0.1.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: F744D8B8D684DBECDB2F3C9DA6199645DDE99A9E636FC3C4F30E9D2124C31C35DCD4F4C682BA163B878892A0E877F388538DD8D8A2A51D3D1DE38B8794659BC1
//------------------------------------------------------------------------
import java.util.Date;


public interface UBKDateTimeConverter
{
    java.util.Date convertDateTime(String strDate);
    java.util.Date convertTime(String strDate);
    java.util.Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}